import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const _translations = {
    'en': {
      'home': 'Home',
      'exercises': 'Exercises',
      'recordings': 'Recordings',
      'profile': 'Profile',
      'greeting': 'Hey',
      'total_sessions': 'Total Sessions',
      'avg_score': 'Avg. Score',
      'practice_time': 'Practice Time',
      'start_practice': 'Start Practice',
      'settings': 'Settings',
      'notifications': 'Notifications',
      'language': 'Language',
      'devices': 'Devices',
      'audio_settings': 'Audio Settings',
      'help_support': 'Help & Support',
      'about': 'About',
      'sign_out': 'Sign Out',
      'sign_out_confirmation': 'Are you sure you want to sign out?',
      'musician': 'Musician',
      'full_name': 'Full Name',
      'bio': 'Bio',
      'edit_profile': 'Edit Profile',
      'save': 'Save',
      'cancel': 'Cancel',
      'connected': 'Connected',
      'disconnected': 'Disconnected',
      'last_connected': 'Last connected',
      'push_notifications': 'Push Notifications',
      'push_notifications_desc': 'Receive alerts for practice reminders',
      'achievement_alerts': 'Achievement Alerts',
      'achievement_alerts_desc': 'Get notified when you hit milestones',
      'weekly_summary': 'Weekly Summary',
      'weekly_summary_desc': 'Get a summary of your progress',
      'new_exercises': 'New Exercises',
      'new_exercises_desc': 'Be the first to know about new content',
      'version': 'Version',
      'terms_service': 'Terms of Service',
      'terms_service_desc': 'Read our legally binding terms',
      'privacy_policy': 'Privacy Policy',
      'privacy_policy_desc': 'How we handle your data',
      'open_source': 'Open Source Licenses',
      'open_source_desc': 'Third-party libraries we use',
      'faq': 'FAQ',
      'faq_desc': 'Frequently asked questions',
      'contact_support': 'Contact Support',
      'contact_support_desc': 'Get help from our team',
      'tutorials': 'Tutorials',
      'tutorials_desc': 'Learn how to use the app',
      'report_bug': 'Report a Bug',
      'error_bug_desc': 'Let us know if something is wrong',
      'profile_updated_success': 'Profile updated successfully!',
      'error_updating_profile': 'Error updating profile',
      'avatar_uploaded': 'Avatar uploaded! Save profile to keep changes.',
      'error_uploading_image': 'Error uploading image',
      'recordings_empty_title': 'Your stage is empty',
      'recordings_empty_desc': 'Your recorded sessions will appear here. Start practicing to see your progress!',
      'refresh_library': 'Refresh Library',
      'exercises_title': 'Exercises',
      'recommended_for_you': 'Recommended for You',
      'recent_practice_desc': 'Based on your recent practice sessions',
      'all_exercises': 'All Exercises',
      'difficulty': 'Difficulty',
      'duration': 'Duration',
      'minutes': 'minutes',
      'favorites': 'Favorites',
      'upload_music': 'Upload Music',
      'camera_recommended': 'Camera (Recommended)',
      'camera_desc': 'Scan sheet music using your camera.',
      'from_device': 'From Device',
      'device_desc': 'Upload a PDF or image from your device.',
      'transcribing': 'Transcribing...',
      'name_excerpt': 'Name your excerpt',
      'excerpt_name_hint': 'e.g., G Major Arpeggio',
      'reference_ai_hint': 'This is how you will reference it to the AI.',
      'focus_areas': 'Focus Areas',
      'start_exercise': 'Start Exercise',
      'starting': 'Starting',
      'category_all': 'All',
      'category_scales': 'Scales',
      'category_arpeggios': 'Arpeggios',
      'category_sight_reading': 'Sight Reading',
      'category_technique': 'Technique',
      'category_rhythm': 'Rhythm',
      'category_tone': 'Tone',
      'difficulty_beginner': 'Beginner',
      'difficulty_intermediate': 'Intermediate',
      'difficulty_advanced': 'Advanced',
      'my_devices': 'My Devices',
      'add_new_device': 'Add New Device',
      'past_connected_devices': 'Past Connected Devices',
      'no_saved_devices': 'No saved devices yet',
      'error_removing_device': 'Error removing device',
      'connect_to_device': 'Connect to Device',
      'connect': 'Connect',
      'connection_failed': 'Connection failed',
      'unknown_device': 'Unknown Device',
    },
    'es': {
      'home': 'Inicio',
      'exercises': 'Ejercicios',
      'recordings': 'Grabaciones',
      'profile': 'Perfil',
      'greeting': 'Hola',
      'total_sessions': 'Sesiones Totales',
      'avg_score': 'Puntuación Promedio',
      'practice_time': 'Tiempo de Práctica',
      'start_practice': 'Empezar Práctica',
      'settings': 'Ajustes',
      'notifications': 'Notificaciones',
      'language': 'Idioma',
      'devices': 'Dispositivos',
      'audio_settings': 'Ajustes de Audio',
      'help_support': 'Ayuda y Soporte',
      'about': 'Acerca de',
      'sign_out': 'Cerrar Sesión',
      'sign_out_confirmation': '¿Estás seguro de que quieres cerrar sesión?',
      'musician': 'Músico',
      'full_name': 'Nombre Completo',
      'bio': 'Biografía',
      'edit_profile': 'Editar Perfil',
      'save': 'Guardar',
      'cancel': 'Cancelar',
      'connected': 'Conectado',
      'disconnected': 'Desconectado',
      'last_connected': 'Última conexión',
      'push_notifications': 'Notificaciones Push',
      'push_notifications_desc': 'Recibir alertas de recordatorios de práctica',
      'achievement_alerts': 'Alertas de Logros',
      'achievement_alerts_desc': 'Recibir notificaciones al alcanzar hitos',
      'weekly_summary': 'Resumen Semanal',
      'weekly_summary_desc': 'Obtén un resumen de tu progreso',
      'new_exercises': 'Nuevos Ejercicios',
      'new_exercises_desc': 'Sé el primero en saber sobre nuevo contenido',
      'version': 'Versión',
      'terms_service': 'Términos de Servicio',
      'terms_service_desc': 'Lee nuestros términos legalmente vinculantes',
      'privacy_policy': 'Política de Privacidad',
      'privacy_policy_desc': 'Cómo manejamos tus datos',
      'open_source': 'Licencias de Código Abierto',
      'open_source_desc': 'Bibliotecas de terceros que usamos',
      'faq': 'Preguntas Frecuentes',
      'faq_desc': 'Preguntas frecuentes',
      'contact_support': 'Contactar Soporte',
      'contact_support_desc': 'Obtén ayuda de nuestro equipo',
      'tutorials': 'Tutoriales',
      'tutorials_desc': 'Aprende cómo usar la aplicación',
      'report_bug': 'Informar un Error',
      'report_bug_desc': 'Cuéntanos si algo está mal',
      'profile_updated_success': '¡Perfil actualizado con éxito!',
      'error_updating_profile': 'Error al actualizar el perfil',
      'avatar_uploaded': '¡Avatar subido! Guarda el perfil para mantener los cambios.',
      'error_uploading_image': 'Error al subir la imagen',
      'recordings_empty_title': 'Tu escenario está vacío',
      'recordings_empty_desc': 'Tus sesiones grabadas aparecerán aquí. ¡Empieza a practicar para ver tu progreso!',
      'refresh_library': 'Actualizar Biblioteca',
      'exercises_title': 'Ejercicios',
      'recommended_for_you': 'Recomendado para ti',
      'recent_practice_desc': 'Basado en tus sesiones de práctica recientes',
      'all_exercises': 'Todos los Ejercicios',
      'difficulty': 'Dificultad',
      'duration': 'Duración',
      'minutes': 'minutos',
      'favorites': 'Favoritos',
      'upload_music': 'Subir Música',
      'camera_recommended': 'Cámara (Recomendado)',
      'camera_desc': 'Escanear partituras con tu cámara.',
      'from_device': 'Desde Dispositivo',
      'device_desc': 'Subir un PDF o imagen desde tu dispositivo.',
      'transcribing': 'Transcribiendo...',
      'name_excerpt': 'Nombra tu fragmento',
      'excerpt_name_hint': 'ej., Arpegio en Sol Mayor',
      'reference_ai_hint': 'Así es como se lo referenciarás a la IA.',
      'focus_areas': 'Áreas de Enfoque',
      'start_exercise': 'Empezar Ejercicio',
      'starting': 'Empezando',
      'category_all': 'Todos',
      'category_scales': 'Escalas',
      'category_arpeggios': 'Arpegios',
      'category_sight_reading': 'Lectura a primera vista',
      'category_technique': 'Técnica',
      'category_rhythm': 'Ritmo',
      'category_tone': 'Tono',
      'difficulty_beginner': 'Principiante',
      'difficulty_intermediate': 'Intermedio',
      'difficulty_advanced': 'Avanzado',
      'my_devices': 'Mis Dispositivos',
      'add_new_device': 'Añadir Nuevo Dispositivo',
      'past_connected_devices': 'Dispositivos Conectados Anteriormente',
      'no_saved_devices': 'Aún no hay dispositivos guardados',
      'error_removing_device': 'Error al eliminar el dispositivo',
      'connect_to_device': 'Conectar a Dispositivo',
      'connect': 'Conectar',
      'connection_failed': 'Error de conexión',
      'unknown_device': 'Dispositivo Desconocido',
    },
    'fr': {
      'home': 'Accueil',
      'exercises': 'Exercices',
      'recordings': 'Enregistrements',
      'profile': 'Profil',
      'greeting': 'Salut',
      'total_sessions': 'Total des Sessions',
      'avg_score': 'Score Moyen',
      'practice_time': 'Temps de Pratique',
      'start_practice': 'Commencer la Pratique',
      'settings': 'Paramètres',
      'notifications': 'Notifications',
      'language': 'Langue',
      'devices': 'Appareils',
      'audio_settings': 'Paramètres Audio',
      'help_support': 'Aide et Support',
      'about': 'À propos',
      'sign_out': 'Déconnexion',
      'sign_out_confirmation': 'Êtes-vous sûr de vouloir vous déconnecter ?',
      'musician': 'Musicien',
      'full_name': 'Nom Complet',
      'bio': 'Bio',
      'edit_profile': 'Modifier le Profil',
      'save': 'Enregistrer',
      'cancel': 'Annuler',
      'connected': 'Connecté',
      'disconnected': 'Déconnecté',
      'last_connected': 'Dernière connexion',
      'push_notifications': 'Notifications Push',
      'push_notifications_desc': 'Recevoir des alertes pour les rappels de pratique',
      'achievement_alerts': 'Alertes de Réussite',
      'achievement_alerts_desc': 'Soyez notifié lorsque vous atteignez des jalons',
      'weekly_summary': 'Résumé Hebdomadaire',
      'weekly_summary_desc': 'Obtenez un résumé de vos progrès',
      'new_exercises': 'Nouveaux Exercices',
      'new_exercises_desc': 'Soyez le premier à connaître le nouveau contenu',
      'version': 'Version',
      'terms_service': 'Conditions d\'utilisation',
      'terms_service_desc': 'Lisez nos conditions juridiquement contraignantes',
      'privacy_policy': 'Politique de Confidentialité',
      'privacy_policy_desc': 'Comment nous traitons vos données',
      'open_source': 'Licences Open Source',
      'open_source_desc': 'Bibliothèques tierces que nous utilisons',
      'faq': 'FAQ',
      'faq_desc': 'Questions fréquemment posées',
      'contact_support': 'Contacter le Support',
      'contact_support_desc': 'Obtenez de l\'aide de notre équipe',
      'tutorials': 'Tutoriels',
      'tutorials_desc': 'Apprenez à utiliser l\'application',
      'report_bug': 'Signaler un Bug',
      'report_bug_desc': 'Faites-nous savoir si quelque chose ne va pas',
      'profile_updated_success': 'Profil mis à jour avec succès !',
      'error_updating_profile': 'Erreur lors de la mise à jour du profil',
      'avatar_uploaded': 'Avatar téléchargé ! Enregistrez le profil pour conserver les modifications.',
      'error_uploading_image': 'Erreur lors du téléchargement de l\'image',
      'recordings_empty_title': 'Votre scène est vide',
      'recordings_empty_desc': 'Vos sessions enregistrées apparaîtront ici. Commencez à pratiquer pour voir vos progrès !',
      'refresh_library': 'Actualiser la Bibliothèque',
      'exercises_title': 'Exercices',
      'recommended_for_you': 'Recommandé pour vous',
      'recent_practice_desc': 'Basé sur vos récentes sessions de pratique',
      'all_exercises': 'Tous les Exercices',
      'difficulty': 'Difficulté',
      'duration': 'Durée',
      'minutes': 'minutes',
      'favorites': 'Favoris',
      'upload_music': 'Télécharger de la Musique',
      'camera_recommended': 'Caméra (Recommandé)',
      'camera_desc': 'Scannez une partition avec votre caméra.',
      'from_device': 'Depuis l\'Appareil',
      'device_desc': 'Téléchargez un PDF ou une image.',
      'transcribing': 'Transcription...',
      'name_excerpt': 'Nommez votre extrait',
      'excerpt_name_hint': 'ex: Arpège en Sol Majeur',
      'reference_ai_hint': 'C\'est ainsi que vous le nommerez à l\'IA.',
      'focus_areas': 'Domaines d\'intérêt',
      'start_exercise': 'Commencer l\'Exercice',
      'starting': 'Lancement de',
      'category_all': 'Tous',
      'category_scales': 'Gammes',
      'category_arpeggios': 'Arpèges',
      'category_sight_reading': 'Lecture à vue',
      'category_technique': 'Technique',
      'category_rhythm': 'Rythme',
      'category_tone': 'Timbre',
      'difficulty_beginner': 'Débutant',
      'difficulty_intermediate': 'Intermédiaire',
      'difficulty_advanced': 'Avancé',
      'my_devices': 'Mes Appareils',
      'add_new_device': 'Ajouter un Nouvel Appareil',
      'past_connected_devices': 'Appareils Précédemment Connectés',
      'no_saved_devices': 'Pas encore d\'appareils enregistrés',
      'error_removing_device': 'Erreur lors de la suppression de l\'appareil',
      'connect_to_device': 'Se Connecter à l\'Appareil',
      'connect': 'Se Connecter',
      'connection_failed': 'La connexion a échoué',
      'unknown_device': 'Appareil Inconnu',
    },
    'de': {
      'home': 'Home',
      'exercises': 'Übungen',
      'recordings': 'Aufnahmen',
      'profile': 'Profil',
      'greeting': 'Hallo',
      'total_sessions': 'Gesamte Sitzungen',
      'avg_score': 'Durchschnittswert',
      'practice_time': 'Übungszeit',
      'start_practice': 'Übung Starten',
      'settings': 'Einstellungen',
      'notifications': 'Benachrichtigungen',
      'language': 'Sprache',
      'devices': 'Geräte',
      'audio_settings': 'Audio-Einstellungen',
      'help_support': 'Hilfe & Support',
      'about': 'Über',
      'sign_out': 'Abmelden',
      'sign_out_confirmation': 'Sind Sie sicher, dass Sie sich abmelden möchten?',
      'musician': 'Musiker',
      'full_name': 'Vollständiger Name',
      'bio': 'Bio',
      'edit_profile': 'Profil Bearbeiten',
      'save': 'Speichern',
      'cancel': 'Abbrechen',
      'connected': 'Verbunden',
      'disconnected': 'Getrennt',
      'last_connected': 'Zuletzt verbunden',
      'push_notifications': 'Push-Benachrichtigungen',
      'push_notifications_desc': 'Erhalten Sie Erinnerungen für das Üben',
      'achievement_alerts': 'Erfolgsbenachrichtigungen',
      'achievement_alerts_desc': 'Lassen Sie sich bei Meilensteinen benachrichtigen',
      'weekly_summary': 'Wöchentliche Zusammenfassung',
      'weekly_summary_desc': 'Erhalten Sie eine Zusammenfassung Ihres Fortschritts',
      'new_exercises': 'Neue Übungen',
      'new_exercises_desc': 'Erfahren Sie als Erster von neuen Inhalten',
      'version': 'Version',
      'terms_service': 'Nutzungsbedingungen',
      'terms_service_desc': 'Lesen Sie unsere rechtlich bindenden Bedingungen',
      'privacy_policy': 'Datenschutzerklärung',
      'privacy_policy_desc': 'Wie wir mit Ihren Daten umgehen',
      'open_source': 'Open-Source-Lizenzen',
      'open_source_desc': 'Von uns verwendete Drittanbieter-Bibliotheken',
      'faq': 'FAQ',
      'faq_desc': 'Häufig gestellte Fragen',
      'contact_support': 'Support kontaktieren',
      'contact_support_desc': 'Holen Sie sich Hilfe von unserem Team',
      'tutorials': 'Tutorials',
      'tutorials_desc': 'Lernen Sie die App-Bedienung',
      'report_bug': 'Fehler melden',
      'report_bug_desc': 'Lassen Sie uns wissen, wenn etwas nicht stimmt',
      'profile_updated_success': 'Profil erfolgreich aktualisiert!',
      'error_updating_profile': 'Fehler beim Aktualisieren des Profils',
      'avatar_uploaded': 'Avatar hochgeladen! Speichern Sie das Profil, um die Änderungen zu behalten.',
      'error_uploading_image': 'Fehler beim Hochladen des Bildes',
      'recordings_empty_title': 'Ihre Bühne ist leer',
      'recordings_empty_desc': 'Ihre aufgezeichneten Sitzungen werden hier angezeigt. Fangen Sie an zu üben, um Ihren Fortschritt zu sehen!',
      'refresh_library': 'Bibliothek aktualisieren',
      'exercises_title': 'Übungen',
      'recommended_for_you': 'Empfohlen für Sie',
      'recent_practice_desc': 'Basierend auf Ihren letzten Übungssitzungen',
      'all_exercises': 'Alle Übungen',
      'difficulty': 'Schwierigkeit',
      'duration': 'Dauer',
      'minutes': 'Minuten',
      'favorites': 'Favoriten',
      'upload_music': 'Musik Hochladen',
      'camera_recommended': 'Kamera (Empfohlen)',
      'camera_desc': 'Noten mit der Kamera scannen.',
      'from_device': 'Vom Gerät',
      'device_desc': 'PDF oder Bild vom Gerät hochladen.',
      'transcribing': 'Transkribieren...',
      'name_excerpt': 'Excerpt benennen',
      'excerpt_name_hint': 'z.B. G-Dur Arpeggio',
      'reference_ai_hint': 'So bezeichnen Sie es gegenüber der KI.',
      'focus_areas': 'Schwerpunkte',
      'start_exercise': 'Übung Starten',
      'starting': 'Starte',
      'category_all': 'Alle',
      'category_scales': 'Tonleitern',
      'category_arpeggios': 'Arpeggios',
      'category_sight_reading': 'Blattspiel',
      'category_technique': 'Technik',
      'category_rhythm': 'Rhythmus',
      'category_tone': 'Klang',
      'difficulty_beginner': 'Anfänger',
      'difficulty_intermediate': 'Fortgeschritten',
      'difficulty_advanced': 'Profi',
      'my_devices': 'Meine Geräte',
      'add_new_device': 'Neues Gerät hinzufügen',
      'past_connected_devices': 'Zuletzt verbundene Geräte',
      'no_saved_devices': 'Noch keine Geräte gespeichert',
      'error_removing_device': 'Fehler beim Entfernen des Geräts',
      'connect_to_device': 'Mit Gerät verbinden',
      'connect': 'Verbinden',
      'connection_failed': 'Verbindung fehlgeschlagen',
      'unknown_device': 'Unbekanntes Gerät',
    },
    'ja': {
      'home': 'ホーム',
      'exercises': 'エクササイズ',
      'recordings': '録音',
      'profile': 'プロフィール',
      'greeting': 'こんにちは',
      'total_sessions': '総セッション数',
      'avg_score': '平均スコア',
      'practice_time': '練習時間',
      'start_practice': '練習を開始',
      'settings': '設定',
      'notifications': '通知',
      'language': '言語',
      'devices': 'デバイス',
      'audio_settings': 'オーディオ設定',
      'help_support': 'ヘルプとサポート',
      'about': 'アプリについて',
      'sign_out': 'サインアウト',
      'sign_out_confirmation': '本当にサインアウトしますか？',
      'musician': 'ミュージシャン',
      'full_name': '氏名',
      'bio': '自己紹介',
      'edit_profile': 'プロフィール編集',
      'save': '保存',
      'cancel': 'キャンセル',
      'connected': '接続済み',
      'disconnected': '未接続',
      'last_connected': '最終接続',
      'push_notifications': 'プッシュ通知',
      'push_notifications_desc': '練習のリマインダー通知を受け取る',
      'achievement_alerts': '実績アラート',
      'achievement_alerts_desc': 'マイルストーン達成時に通知を受け取る',
      'weekly_summary': '週間サマリー',
      'weekly_summary_desc': '進捗状況のまとめを受け取る',
      'new_exercises': '新しいエクササイズ',
      'new_exercises_desc': '新しいコンテンツをいち早く知る',
      'version': 'バージョン',
      'terms_service': '利用規約',
      'terms_service_desc': '法的拘束力のある規約を確認する',
      'privacy_policy': 'プライバシーポリシー',
      'privacy_policy_desc': 'データの取り扱いについて',
      'open_source': 'オープンソースライセンス',
      'open_source_desc': '使用しているサードパーティ製ライブラリ',
      'faq': 'よくある質問',
      'faq_desc': '頻繁に寄せられる質問',
      'contact_support': 'サポートに連絡',
      'contact_support_desc': 'チームからサポートを受ける',
      'tutorials': 'チュートリアル',
      'tutorials_desc': 'アプリの使い方を学ぶ',
      'report_bug': 'バグを報告',
      'report_bug_desc': '問題がある場合はお知らせください',
      'profile_updated_success': 'プロフィールが正常に更新されました！',
      'error_updating_profile': 'プロフィールの更新中にエラーが発生しました',
      'avatar_uploaded': 'アバターがアップロードされました！変更を保存するにはプロフィールを保存してください。',
      'error_uploading_image': '画像のアップロード中にエラーが発生しました',
      'recordings_empty_title': 'ステージは空っぽです',
      'recordings_empty_desc': '録音されたセッションがここに表示されます。練習を始めて進捗を確認しましょう！',
      'refresh_library': 'ライブラリを更新',
      'exercises_title': 'エクササイズ',
      'recommended_for_you': 'あなたへのおすすめ',
      'recent_practice_desc': '最近の練習セッションに基づいています',
      'all_exercises': 'すべてのエクササイズ',
      'difficulty': '難易度',
      'duration': '再生時間',
      'minutes': '分',
      'favorites': 'お気に入り',
      'upload_music': '音楽をアップロード',
      'camera_recommended': 'カメラ（推奨）',
      'camera_desc': 'カメラで楽譜をスキャンします。',
      'from_device': 'デバイスから',
      'device_desc': 'デバイスからPDFや画像をアップロードします。',
      'transcribing': '文字起こし中...',
      'name_excerpt': '抜粋に名前を付ける',
      'excerpt_name_hint': '例：ト長調のアルペジオ',
      'reference_ai_hint': 'これは、AIに参照する方法です。',
      'focus_areas': '重点エリア',
      'start_exercise': 'エクササイズを開始',
      'starting': '開始中：',
      'category_all': 'すべて',
      'category_scales': 'スケール',
      'category_arpeggios': 'アルペジオ',
      'category_sight_reading': '初見演奏',
      'category_technique': 'テクニック',
      'category_rhythm': 'リズム',
      'category_tone': 'トーン',
      'difficulty_beginner': '初心者',
      'difficulty_intermediate': '中級者',
      'difficulty_advanced': '上級者',
      'my_devices': 'マイデバイス',
      'add_new_device': '新しいデバイスを追加',
      'past_connected_devices': '過去に接続したデバイス',
      'no_saved_devices': '保存されたデバイスはまだありません',
      'error_removing_device': 'デバイスの削除中にエラーが発生しました',
      'connect_to_device': 'デバイスに接続',
      'connect': '接続',
      'connection_failed': '接続に失敗しました',
      'unknown_device': '不明なデバイス',
    },
  };

  String translate(String key) {
    return _translations[locale.languageCode]?[key] ?? _translations['en']![key] ?? key;
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return ['en', 'es', 'fr', 'de', 'ja'].contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) {
    return SynchronousFuture<AppLocalizations>(AppLocalizations(locale));
  }

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}
